FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.base.txt /tmp/requirements.base.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.base.txt